# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c88ffeb0e21fc45e86f867c8b0e83e62c81d7e567bee1b1b491db7d66e16d8ecbbdfeae9b569bb6f83a82f7b1162f6512434c6b40f4721af80c02eeeb527891

test:
  secret_key_base: d022bc3cc03c053ca4275cdeb5927dfffb199ded5beded3498e1247c4d910ba6bea5397b125e38f62d333b6de6f455781391609bfb83c7426e5751a3eb5deb38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
