# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a231c1d187257263ba8c4fa57b7bfc8f89c3cd9d37996f164ca4bd2e7a4f30c748e4ef5bb56a255a8598eee269b9e818aec4a348042880e958717dfcf118aff8

test:
  secret_key_base: 21c3a8b9e0b2f55f053cb55ee0815466d7df68e4023a64c3f48c68ed225914975e32c02173548b143c8b22ea267d634fd489ae1c204c1cda960aa71d9ee3f03f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
